language: objective-c
osx_image: xcode8.3
rvm:
- 2.2

before_install:
- chmod a+x ./scripts/*.sh

install:
- travis_retry ./scripts/install_unity.sh

script:
- ./scripts/build_project.sh rapid-router-unity
